#! /usr/bin/env bash

# This script generates the sources and headers lists for CMake.
# It scans the 'include' and 'lib' directories for .h/.hpp and .cpp files respectively,
# and writes the lists to 'cmake/SourcesAndHeaders.cmake'.
# Entry-point files live in 'src/' and 'examples/' and are not included here.

INCLUDE_DIR="include"
SRC_DIR="lib"
TEST_DIR="test"
OUTPUT_FILE="cmake/SourcesAndHeaders.cmake"
HEADER_EXTENSIONS=("h" "hpp")
SOURCE_EXTENSIONS=("cpp")
HEADER_LIST_VAR="HEADERS"
SOURCE_LIST_VAR="SOURCES"
TEST_SOURCE_LIST_VAR="TEST_SOURCES"

# Prints a sorted, newline-separated list of files under <dir> that match any of
# the extensions. Uses -print0 for safety with spaces; output is reproducible.
# Usage: generate_file_list <dir> <ext1> [ext2 ...]
generate_file_list() {
    local dir="$1"
    shift
    local exts=("$@")

    [[ -d "$dir" ]] || return 0
    [[ ${#exts[@]} -gt 0 ]] || return 0

    local find_args=("$dir" -type f '(' -name "*.${exts[0]}")
    for ((i = 1; i < ${#exts[@]}; ++i)); do
        find_args+=( -o -name "*.${exts[i]}" )
    done
    find_args+=( ')' -print0 )

    find "${find_args[@]}" | tr '\0' '\n' | sed '/^$/d' | LC_ALL=C sort
}

# Create the output CMake file. Overwrite if exists.
mkdir -p "$(dirname "$OUTPUT_FILE")"
echo "# Auto-generated by tools/generate_sources_and_headers.sh" > "$OUTPUT_FILE"

# Write headers list
echo "set(${HEADER_LIST_VAR}" >> "$OUTPUT_FILE"
generate_file_list "$INCLUDE_DIR" "${HEADER_EXTENSIONS[@]}" | sed 's/^/  /' >> "$OUTPUT_FILE"
echo ")" >> "$OUTPUT_FILE"
echo >> "$OUTPUT_FILE"

# Write sources list (library code only — entry points live in src/ and examples/)
echo "set(${SOURCE_LIST_VAR}" >> "$OUTPUT_FILE"
generate_file_list "$SRC_DIR" "${SOURCE_EXTENSIONS[@]}" | sed 's/^/  /' >> "$OUTPUT_FILE"
echo ")" >> "$OUTPUT_FILE"
echo >> "$OUTPUT_FILE"

# Optionally include test sources if the test dir exists
if [[ -d "$TEST_DIR" ]]; then
    echo "set(${TEST_SOURCE_LIST_VAR}" >> "$OUTPUT_FILE"
    generate_file_list "$TEST_DIR" "${SOURCE_EXTENSIONS[@]}" | sed 's/^/  /' >> "$OUTPUT_FILE"
    echo ")" >> "$OUTPUT_FILE"
fi

echo "Wrote $OUTPUT_FILE"
